### ISSUE TITLE
Merge the two

### ISSUE THREAD

**Issue by SleepDaemon** [RoseTheFlower/MetroSteam#12]
This is really not an issue but a suggestion to merge my repo https://github.com/SleepDaemon/SteamDarkMode, with yours. I like the download page and solves this problem ,https://github.com/AikoMidori/steam-library/issues/14, that is currently in the skin. I did find a cheap solution but it really doesn't look nice compare to what you have. I've already added the friend.css, just need to figure out how to merge the library.css together.

**Comment by RoseTheFlower** [comment]
Looking at the library skin of your repo, all I can see is that it just downloads Shiina's library skin. I don't think that fully merging my skin with Shiina's is possible, because quite a number of Shiina's choices are inconsistent with the style of the original Metro skin. The rounded corners of almost everything are one of them, for example.

You could ask about any specific elements and I can point at them if you are looking to incorporate any ideas.

**Comment by SleepDaemon** [comment]
Just really want the download window, nothing else really. Shiina uses !import, and they do this for the download window as well. So I'll probably just remove the !import for download, grab your download window elements and paste them. I also make sure the config.css that comes with Shiina's doesn't interfere. I'll see mess around tomorrow and see where I get and let you know.

**Comment by RoseTheFlower** [comment]
I'll close this, as I think that it is now possible to use SFP along with something like webkit.css for the Steam store pages and my CSS for the rest. Either way, it's not an issue specific to my skin.
