### ISSUE TITLE
SFP - Beta - Library: Right-Click and Dropdown Menu's not Skinning

### ISSUE THREAD

**Issue by Zacam** [RoseTheFlower/MetroSteam#37]
Updated code to latest after a Steam Client Update

Beta Channel, Steam Version: 1721691653 (Mon July 22)
API: SteamClient021
SFP Ver: 0.0.54
Skin Update: Commit 6f35bf2, pulled July 23rd 2200 Pacific

Affected Area: All "Top" menu drop-down's, though "highlight" of elements in menu's appears to be happening.
(Store, Library, Community, User; Steam, View, Friends, Game, Help)

Also Affected: Right-Click menu in Library

I've attempted restarting SFP and Steam multiple times, since sometimes Steam can start without any skinning with SFP, but this has been consistent when all other theming has been applied.

**Comment by RoseTheFlower** [comment]
The beta is currently unsupported. The cause of the issues is [Valve having randomized the class names](https://www.reddit.com/r/Steam/comments/1ba101m/valve_may_potentially_kill_theme_customization_in/) again.

In order to support the beta, I'd have to create a separate branch in the repo, as the old class names are still applicable to the stable version. Moreover, I'd have to somehow manually get the updated class names and replace them. Hopefully there is a way to automate this, with some progress already made by @ricewind012 in [steam-theming-utils](https://github.com/ricewind012/steam-theming-utils).

In the absence of a GitHub Actions or a similar way to do this, I don't think I will have the will to manually do the work every time this happens. At the moment I'm also not too eager to install new software just for the task.

**Comment by RoseTheFlower** [comment]
ricewind012 shared two files, each containing the randomized classes mapped to their readable form. The files look like this:

![image](https://github.com/user-attachments/assets/f1c668ee-d25e-461b-a717-a06ed5b2c414)

I think I managed to convert them after a few hours of trying to make them into a find and replace script (basically removed everything but the differences, made into an `old,new` list, then used that to find and replace). You can get the new files via the beta branch - https://github.com/RoseTheFlower/MetroSteam/tree/steam-beta

**Comment by RoseTheFlower** [comment]
Also, the Enable Beta Steam CSS Translations toggle of CSSLoader seems to work for me now with no need to switch to my beta branch.

**Comment by RoseTheFlower** [comment]
The beta was made stable. Works fine with my updated CSS.
