### ISSUE TITLE
Hide URL Bar and two other questions

### ISSUE THREAD

**Issue by ZachFett** [RoseTheFlower/MetroSteam#46]
Sorry to post this as an "issue" when it's more of just a question, but you don't have a Discussions tab on here. How would I go about hiding the URL bar that's visible when on any store or community page? I tried adding "--option-display-urlbar: none;" but that isn't working.

Also not related to this question, but regarding "Your own code (advanced)" is it possible to enable automatic updates, but have something in my own custom.css that tells it not to load certain lines from your css? There's a few lines that I have to remove every time I update the skin to try to get it to look as close to my old version of Metro as I can, like reverting the right click context menu changes and some color/font size-related lines for the game list.

Lastly, any idea why the library hero images are now dimmed for me when using your theme? I don't think it did this before I updated...
<img width="1114" alt="steamwebhelper_10-01-2024_22-18-57" src="https://github.com/user-attachments/assets/03b8a9a4-4477-4755-821c-3bc30c264420">

**Comment by RoseTheFlower** [comment]
Hi Zach, from a quick look at the code, which is no longer easy to read due to the class randomization, I don't know if Steam makes a distinction between its own and other pages anymore. The class containing the URL text is MZPxEZcxAGtPDf1NYtouS. The parent element you would want to remove is probably _1rDh5rXSFZJOqCa4UpnI4z. Using JavaScript, it should be possible to check the child for specific text like https://steamcommunity.com/ and remove the parent if the condition is met. My skin doesn't use JS, so it may be a question best asked [on the Metro Discord](https://discord.gg/ynK6DuJz). I'm not great at JavaScript, so while I could suggest something, I don't know if it would be the best way.

On your question about updates, you could introduce your own overrides matching the original Valve code via custom.css. Off the top of my head, I can't think of another way to just ignore specific parts. Again, maybe someone on the Discord would have better ideas.

On the dimming, see #23.

**Comment by ZachFett** [comment]
Perfect, thank you so much for the info!
